### ISSUE TITLE
PHP 7.x issues

### ISSUE THREAD

**Issue by zensudo** [OpenEstate/OpenEstate-PHP-Wrapper-WordPress#3]
Wrapper does not work in PHP 7.2

**Comment by pinhead84** [comment]
I'm not sure, if the root of the problem is in the WordPress plugin or in the exported PHP scripts. Can you access the exported PHP scripts directly through your web browser without getting PHP errors?

What kind of errors do you get? - Can you please send me the error log entries?

Which version of the PHP export scripts are you using? - With the last update of OpenEstate-ImmoTool (1.0-beta43) we're providing a modified version of the PHP export scripts ([1.7.0](https://github.com/OpenEstate/OpenEstate-PHP-Export/tree/v1.7.0) and [2.0-beta1](https://github.com/OpenEstate/OpenEstate-PHP-Export/tree/v2.0-beta1)), that have been tested with PHP 7.2. Maybe you just need to update these scripts.

**Comment by zensudo** [comment]
I'm sorry, please close this case. Everything is fine. The Error was my fault.
